### ISSUE TITLE
brew install kong fails, Error linking gcc_s.10.4

### ISSUE THREAD

**Issue by andersjanmyr** [Mashape/homebrew-kong#11]
Hi, `brew install kong` fails with the following error.

  System Version:	OS X 10.10.5 (14F27)
  Kernel Version:	Darwin 14.5.0

    $ brew install kong
    ==> Installing kong from mashape/homebrew-kong
    ==> Installing dependencies for mashape/kong/kong: mashape/kong/ngx_openresty
    ==> Installing mashape/kong/kong dependency: mashape/kong/ngx_openresty
    ==> Downloading http://openresty.org/download/ngx_openresty-1.9.3.1.tar.gz
    Already downloaded: /Library/Caches/Homebrew/ngx_openresty-1.9.3.1.tar.gz
    ==> Patching
    patching file bundle/nginx-1.9.3/src/event/ngx_event_openssl.c
    Hunk #1 succeeded at 1206 (offset 85 lines).
    patching file bundle/nginx-1.9.3/src/event/ngx_event_openssl.h
    ==> curl -s -L -o /private/tmp/ngx_openresty20151008-96271-l7uxma/ngx_openresty-1.9.3.1/ssl-cert-by-lua.tar.gz https://github.com/open
    ==> tar -xzf ssl-cert-by-lua.tar.gz
    ==> rm -rf bundle/ngx_lua-0.9.16/*
    ==> cp -R lua-nginx-module-ssl-cert-by-lua/* bundle/ngx_lua-0.9.16/
    ==> ./configure --prefix=/usr/local/Cellar/ngx_openresty/1.9.3.1 --with-ipv6 --with-luajit --with-pcre-jit --with-http_ssl_module --wi
    Last 15 lines from /Users/andersjanmyr/Library/Logs/Homebrew/ngx_openresty/05.configure:
    CC        lj_carith.o
    CC        lj_clib.o
    CC        lj_cparse.o
    CC        lj_lib.o
    CC        lj_alloc.o
    CC        lib_aux.o
    CC        lib_package.o
    CC        lib_init.o
    CC        luajit.o
    HOSTLINK  host/minilua
    ld: library not found for -lgcc_s.10.4
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [host/minilua] Error 1
    make: *** [default] Error 2
    ERROR: failed to run command: gmake TARGET_STRIP=@: CCDEBUG=-g CC=cc PREFIX=/usr/local/Cellar/ngx_openresty/1.9.3.1/luajit

**Comment by johnsheehan** [comment]
+1

**Comment by ahmadnassri** [comment]
@andersjanmyr seems like you're missing `gcc`:

```
ld: library not found for -lgcc_s.10.4
```

**Comment by thibaultCha** [comment]
My guess is that you are missing the Xcode tools or that they are updated. This this related issue on Homebrew: https://github.com/Homebrew/homebrew/issues/40653

**Comment by ahmadnassri** [comment]
there's also an issue with homebrew and openssl libs (if you're on `10.11`) https://github.com/Homebrew/homebrew/issues/40519

basically nobody should ever upgrade OSX for at least a year of being out :)

**Comment by andersjanmyr** [comment]
I have both Xcode and xcode command line tools installed.  and I'm using OSX 10.10.5.
The package installer works fine, but I would prefer using brew.

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F27

$ xcode-select -p
/Applications/Xcode.app/Contents/Developer

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by thibaultCha** [comment]
Which version of Xcode? I'm sorry but this issue is not related to the kong homebrew formula. I think you will get more help on Homebrew itself.

**Comment by andersjanmyr** [comment]
I had Xcode version 6 installed and upgraded it to 7.0.1, but it still did not work.
I don't think there is anything wrong with my brew installation since I have been using it for
a long time without issues.

Anyway, it's not a big deal, I can settle for the package install instead.

I may try to do a clean install of brew and then I let you know how it goes. 
Thanks anyway for your time.

**Comment by thibaultCha** [comment]
I don't think it is strictly related to homebrew either but more probably to something deeper like your libraries and gcc installation. Or some incompatibility between then. You see not to be the only one with the issue when homebrew is using gcc. 

Many homebrew formula have a prebuilt binary, or do not compile software the same way, hence why you probably have never encountered it before. 

I ran the install again today and everything went fine for me.

**Comment by thibaultCha** [comment]
Actually I just thought: what happens if you try to compile openresty yourself? Since it is they failing step here

**Comment by andersjanmyr** [comment]
@thibaultCha You are right openresty also fails, I'll try a re-install.
