### ISSUE TITLE
--with-cassandra should install cassandra20 formula

### ISSUE THREAD

**Issue by sepehr** [Mashape/homebrew-kong#16]
As Kong only works with the 2.x branch of Cassandra, `--with-cassandra` options should install `cassandra20` formula instead of `cassandra` which is 3.x.  

I do not file a PR as I'm still having issues running kong with brew. I'm reading that Kong only works with **2.1.x** but `cassandra20` installs **2.0.x**. And I don't see any 2.1.x in brews :(

**Comment by thibaultCha** [comment]
3.x should be fine although for real production usage I would recommend sticking to 2.1/2.2.

Overall, this option was just added as a quick workaround for people who just want to play with Kong on their MacBooks. For a real development setup I would recommend using containers or solutions such as `ccm`.

**Comment by sepehr** [comment]
> 3.x should be fine although for real production usage I would recommend sticking to 2.1/2.2.

I can confirm that kong does not start with homebrew's Cassandra 3.x installed:  

```
$ brew services list
Name        Status  User   Plist
cassandra   started Sepehr /Users/Sepehr/Library/LaunchAgents/homebrew.mxcl.cassandra.plist
cassandra22 stopped
...

$cassandra -v
3.0.2

 $ kong start
[WARN] No configuration at: /etc/kong/kong.yml using default config instead.
[INFO] Using configuration: /usr/local/lib/luarocks/rocks/kong/0.5.3-1/conf/kong.yml
[INFO] Kong version.......0.5.3
       Proxy HTTP port....8000
       Proxy HTTPS port...8443
       Admin API port.....8001
       dnsmasq port.......8053
       Database...........cassandra keepalive=60000 timeout=1000 contact_points=localhost:9042 keyspace=kong
[INFO] Connecting to the database...
[ERR] Cassandra error: Failed to prepare statement: "SELECT * FROM system.schema_keyspaces WHERE keyspace_name = ?;". Cassandra returned error (Invalid): unconfigured table schema_keyspaces
```

But the `homebrew/versions` tap has a new `cassandra22` formula that works just fine with kong.

> Overall, this option was just added as a quick workaround for people who just want to play with Kong on their MacBooks.

I see; I just want to play a little kong too :)

**Comment by thibaultCha** [comment]
Right! I forgot about this but yes, I have seen it a couple times. Indeed, Kong will only run with 2.1 and 2.2 (2.2 being the current most stable version of Cassandra).

**Comment by thibaultCha** [comment]
I removed this option entirely for now because cassandra22 would install 3.0 for me. Added a note that this Formula is not compatible with `cassandra` (hence, 3.0) though.
