### ISSUE TITLE
README should mention luarocks dependencies

### ISSUE THREAD

**Issue by sepehr** [Mashape/homebrew-kong#17]
It's totally undocumented that we need to install luarocks dependencies separately. Don't know if I'm correct but I've been getting a lot of errors and installing luarocks packages fixed the issue. 

`luarocks install ansicolors yaml lub lua-path luasocket luasec lua-cassandra luatz`  

I don't file a PR as I'm not sure if it's an issue or I'm just being a Lua n00b.

**Comment by thibaultCha** [comment]
The formula should install them. Any message while installing it?

**Comment by sepehr** [comment]
No nothing.  

I couldn't install kong from the homebrew. But successfully ran when installed with luarocks directly. The luarocks dependencies on the other hand is not fully supplied; had to install `multipart` and `lua-resty-iputils` packages to run successfully.  

```
$ luarocks install multipart lua-resty-iputils kong
$ kong start

[WARN] No configuration at: /etc/kong/kong.yml using default config instead.
[INFO] Using configuration: /usr/local/lib/luarocks/rocks/kong/0.5.3-1/conf/kong.yml
[INFO] Kong version.......0.5.3
       Proxy HTTP port....8000
       Proxy HTTPS port...8443
       Admin API port.....8001
       dnsmasq port.......8053
       Database...........cassandra keepalive=60000 timeout=1000 contact_points=localhost:9042 keyspace=kong
[INFO] Connecting to the database...
[INFO] dnsmasq started (dnsmasq)
[WARN] ulimit is currently set to "256". For better performance set it to at least "4096" using "ulimit -n"
[OK] Started
```

P.S. I also had to install cassandra 2.1.x manually FTR: #16

**Comment by thibaultCha** [comment]
All those are installed when Kong is being installed (see the make install command). So if they were not installed by homebrew there must be a good reason.

**Comment by thibaultCha** [comment]
Here is what could have happened:

the recent change in Homebrew checking for empty installations could have got into the way of this Formula without initially raising any error. It recently got updated again and the Formula throw an `Error: Empty installation` exception. I just updated it to work around this.

So far I was unable to reproduce a silent failing like you said though, but feel free to give a try to the new Formula after updating Homebrew.

**Comment by sepehr** [comment]
I'll try and see if it works. Thanks.

**Comment by thibaultCha** [comment]
Hi,

Did you give a try to the new Formula from a raw setup (without Luarocks artifacts left from a previous install, I mean)?

**Comment by sepehr** [comment]
Hey, 

Just tried and works fine. Thank you :)

**Comment by thibaultCha** [comment]
Great, thanks!
