### ISSUE TITLE
Openresty update?

### ISSUE THREAD

**Issue by syhily** [Mashape/homebrew-kong#24]
Thank you for your good work on kong, I saw the changlist on kong shows that 0.7.x version is compatible with the latest openresty. So why not update openresty formula.

**Comment by thibaultCha** [comment]
Good point. OpenResty's latest was already available in `--devel` mode, so I just made that the new stable now. Thanks.

**Comment by syhily** [comment]
Cool, thanks. Successfully upgraded.
