### ISSUE TITLE
Kong 0.8.2 is not starting in OSX

### ISSUE THREAD

**Issue by b-rajesh** [Mashape/homebrew-kong#29]
Hi , 
I just installed Kong 0.8.2 in my Mac and i am not able to start the server as usual. I did cleaned my old version , however still having problems. 

```
luajit: /usr/local/share/lua/5.1/kong/cli/utils/logger.lua:5: module 'ansicolors' not found:
no field package.preload['ansicolors']
no file './ansicolors.lua'
no file '/usr/local/Cellar/luajit/2.1_1/share/luajit-2.1.0-beta2/ansicolors.lua'
no file '/usr/local/share/lua/5.1/ansicolors.lua'
no file '/usr/local/share/lua/5.1/ansicolors/init.lua'
no file '/usr/local/Cellar/luajit/2.1_1/share/lua/5.1/ansicolors.lua'
no file '/usr/local/Cellar/luajit/2.1_1/share/lua/5.1/ansicolors/init.lua'
no file './ansicolors.so'
no file '/usr/local/lib/lua/5.1/ansicolors.so'
no file '/usr/local/Cellar/luajit/2.1_1/lib/lua/5.1/ansicolors.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
[C]: in function 'require'
/usr/local/share/lua/5.1/kong/cli/utils/logger.lua:5: in main chunk
[C]: in function 'require'
/usr/local/share/lua/5.1/kong/cli/cmds/version.lua:3: in main chunk
[C]: in function 'require'
/usr/local/bin/kong:54: in main chunk
[C]: at 0x01000018f0
```

**Comment by syhily** [comment]
try reinstall kong like this:
```bash
luarocks purge --tree /usr/local
brew reinstall kong
```

**Comment by b-rajesh** [comment]
thanks , but i am getting the below error

******************************
Error: Failed installing dependency: https://luarocks.org/luacrypto-0.3.2-1.src.rock - Could not find header file for OPENSSL
No file openssl/evp.h in /usr/local/include
No file openssl/evp.h in /usr/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luacrypto OPENSSL_DIR=/usr/local
Updating manifest for /usr/local/lib/luarocks/rocks
pgmoon 1.4.0-1 is now built and installed in /usr/local (license: MIT)

Using https://luarocks.org/luacrypto-0.3.2-1.src.rock... switching to 'build' mode
make: *** [install] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
https://github.com/mashape/homebrew-kong/issues

These open issues may also help:
Kong 0.8.2 is not starting in OSX https://github.com/Mashape/homebrew-kong/issues/29

**Comment by b-rajesh** [comment]
UPDATE:
*************************
I tried install as suggested in the above error
luarocks install luacrypto OPENSSL_DIR=/usr/local/Cellar/OPENSSL/1.0.2h_1/
luarocks install luasec OPENSSL_DIR=/usr/local/Cellar/OPENSSL/1.0.2h_1

still having same problem, I doubt , it is to do with openssl.

When I tried > openssl version -a 
**********
OpenSSL 0.9.8zh 14 Jan 2016
built on: Feb  4 2016
platform: darwin64-x86_64-llvm
options:  bn(64,64) md2(int) rc4(ptr,char) des(idx,cisc,16,int) blowfish(idx)
compiler: -arch x86_64 -fmessage-length=0 -pipe -Wno-trigraphs -fpascal-strings -fasm-blocks -O3 -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DL_ENDIAN -DMD32_REG_T=int -DOPENSSL_NO_IDEA -DOPENSSL_PIC -DOPENSSL_THREADS -DZLIB -mmacosx-version-min=10.6
OPENSSLDIR: "/System/Library/OpenSSL"
**********

It is pointing to different version of openssl (default) rather than point brew installed openssl

**Comment by syhily** [comment]
Never use `/usr/local/Cellar/OPENSSL/1.0.2h_1/` as your openssl install dir, use `/usr/local/opt/openssl` instead.
Use `luarocks install luacrypto --verbose OPENSSL_DIR=/usr/local/opt/openssl` to get the detailed error information

**Comment by b-rajesh** [comment]
luarocks install luacrypto --verbose OPENSSL_DIR=/usr/local/opt/openssl                                                                                                                             16:09

os.execute: 	'curl' -k -f -L --user-agent 'LuaRocks/2.3.0 macosx-x86_64 via curl' --connect-timeout 30 'https://luarocks.org/manifest-5.1.zip' 2> /dev/null 1> '/Users/rajeshbavanantham/.cache/luarocks/https___luarocks.org/manifest-5.1.zip'
Results: 1
  1 (number): 0

os.execute: 	unzip -n '/Users/rajeshbavanantham/.cache/luarocks/https___luarocks.org/manifest-5.1.zip'
Archive:  /Users/rajeshbavanantham/.cache/luarocks/https___luarocks.org/manifest-5.1.zip
  inflating: manifest-5.1
Results: 1
  1 (number): 0
Installing https://luarocks.org/luacrypto-0.3.2-1.src.rock...
Using https://luarocks.org/luacrypto-0.3.2-1.src.rock... switching to 'build' mode

os.execute: 	'curl' -k -f -L --user-agent 'LuaRocks/2.3.0 macosx-x86_64 via curl' --connect-timeout 30 'https://luarocks.org/luacrypto-0.3.2-1.src.rock' 2> /dev/null 1> '/private/tmp/luarocks_luarocks-rock-luacrypto-0.3.2-1-1875/luacrypto-0.3.2-1.src.rock'
Results: 1
  1 (number): 0

os.execute: 	unzip -n '/private/tmp/luarocks_luarocks-rock-luacrypto-0.3.2-1-1875/luacrypto-0.3.2-1.src.rock'
Archive:  /private/tmp/luarocks_luarocks-rock-luacrypto-0.3.2-1-1875/luacrypto-0.3.2-1.src.rock
  inflating: luacrypto-0.3.2-1.rockspec
 extracting: 0.3.2.zip
Results: 1
  1 (number): 0

os.execute: 	unzip -n '0.3.2.zip'
Archive:  0.3.2.zip
0639ea2f65dbe5f11c2d874527f3019ce5293ac5
   creating: luacrypto-0.3.2/
  inflating: luacrypto-0.3.2/.gitignore
 extracting: luacrypto-0.3.2/AUTHORS
  inflating: luacrypto-0.3.2/CMakeLists.txt
  inflating: luacrypto-0.3.2/COPYING
  inflating: luacrypto-0.3.2/ChangeLog
  inflating: luacrypto-0.3.2/INSTALL
  inflating: luacrypto-0.3.2/Makefile.am
  inflating: luacrypto-0.3.2/Makefile.in
 extracting: luacrypto-0.3.2/NEWS
  inflating: luacrypto-0.3.2/README
  inflating: luacrypto-0.3.2/aclocal.m4
  inflating: luacrypto-0.3.2/config.guess
  inflating: luacrypto-0.3.2/config.h.in
  inflating: luacrypto-0.3.2/config.sub
  inflating: luacrypto-0.3.2/configure
  inflating: luacrypto-0.3.2/configure.ac
  inflating: luacrypto-0.3.2/depcomp
  inflating: luacrypto-0.3.2/dist.cmake
   creating: luacrypto-0.3.2/doc/
  inflating: luacrypto-0.3.2/doc/Makefile.am
  inflating: luacrypto-0.3.2/doc/Makefile.in
   creating: luacrypto-0.3.2/doc/us/
  inflating: luacrypto-0.3.2/doc/us/examples.html
  inflating: luacrypto-0.3.2/doc/us/index.html
  inflating: luacrypto-0.3.2/doc/us/license.html
  inflating: luacrypto-0.3.2/doc/us/luacrypto-128.png
  inflating: luacrypto-0.3.2/doc/us/manual.html
  inflating: luacrypto-0.3.2/install-sh
  inflating: luacrypto-0.3.2/ltmain.sh
  inflating: luacrypto-0.3.2/luacrypto.pc.in
  inflating: luacrypto-0.3.2/luacrypto.sln
  inflating: luacrypto-0.3.2/luacrypto.vcproj
   creating: luacrypto-0.3.2/m4/
  inflating: luacrypto-0.3.2/m4/libtool.m4
  inflating: luacrypto-0.3.2/m4/ltoptions.m4
  inflating: luacrypto-0.3.2/m4/ltsugar.m4
  inflating: luacrypto-0.3.2/m4/ltversion.m4
  inflating: luacrypto-0.3.2/m4/lt~obsolete.m4
  inflating: luacrypto-0.3.2/missing
   creating: luacrypto-0.3.2/rockspecs/
  inflating: luacrypto-0.3.2/rockspecs/luacrypto-git-1.rockspec
   creating: luacrypto-0.3.2/src/
  inflating: luacrypto-0.3.2/src/Makefile.am
  inflating: luacrypto-0.3.2/src/Makefile.in
  inflating: luacrypto-0.3.2/src/lcrypto.c
  inflating: luacrypto-0.3.2/src/lcrypto.h
   creating: luacrypto-0.3.2/tests/
  inflating: luacrypto-0.3.2/tests/Makefile.am
  inflating: luacrypto-0.3.2/tests/Makefile.in
   creating: luacrypto-0.3.2/tests/ca/
  inflating: luacrypto-0.3.2/tests/ca/README
  inflating: luacrypto-0.3.2/tests/ca/ca.crt
  inflating: luacrypto-0.3.2/tests/ca/ca.key
  inflating: luacrypto-0.3.2/tests/ca/server.crt
  inflating: luacrypto-0.3.2/tests/ca/server.csr
  inflating: luacrypto-0.3.2/tests/ca/server.key
  inflating: luacrypto-0.3.2/tests/ca/server.key.insecure
  inflating: luacrypto-0.3.2/tests/encrypt.lua
 extracting: luacrypto-0.3.2/tests/message
  inflating: luacrypto-0.3.2/tests/open_seal.lua
  inflating: luacrypto-0.3.2/tests/pkeytest.lua
  inflating: luacrypto-0.3.2/tests/rand.lua
  inflating: luacrypto-0.3.2/tests/run-tests
  inflating: luacrypto-0.3.2/tests/test.lua
 extracting: luacrypto-0.3.2/tests/tmp.rnd
  inflating: luacrypto-0.3.2/tests/x509_ca.lua
Results: 1
  1 (number): 0
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1 -c src/lcrypto.c -o src/lcrypto.o -I/usr/local/opt/openssl/include

os.execute: 	env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC '-I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1' '-c' 'src/lcrypto.c' '-o' 'src/lcrypto.o' '-I/usr/local/opt/openssl/include'
Results: 1
  1 (number): 0
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -bundle -undefined dynamic_lookup -all_load -o crypto.so -L/usr/local/Cellar/luajit/2.1_1/lib src/lcrypto.o -L/usr/local/opt/openssl/lib -Wl,-rpath,/usr/local/opt/openssl/lib: -lcrypto

os.execute: 	env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -bundle -undefined dynamic_lookup -all_load '-o' 'crypto.so' '-L/usr/local/Cellar/luajit/2.1_1/lib' 'src/lcrypto.o' '-L/usr/local/opt/openssl/lib' '-Wl,-rpath,/usr/local/opt/openssl/lib:' '-lcrypto'
Results: 1
  1 (number): 0

io.popen: 	/usr/bin/stat -f '%A' 'crypto.so'

os.execute: 	chmod '755' '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/lib/crypto.so'
Results: 1
  1 (number): 0

io.popen: 	/usr/bin/stat -f '%A' 'doc/Makefile.am'

os.execute: 	chmod '644' '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/doc/Makefile.am'
Results: 1
  1 (number): 0

io.popen: 	/usr/bin/stat -f '%A' 'doc/Makefile.in'

os.execute: 	chmod '644' '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/doc/Makefile.in'
Results: 1
  1 (number): 0

io.popen: 	/usr/bin/stat -f '%A' 'doc/us/examples.html'

os.execute: 	chmod '644' '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/doc/us/examples.html'
Results: 1
  1 (number): 0

io.popen: 	/usr/bin/stat -f '%A' 'doc/us/index.html'

os.execute: 	chmod '644' '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/doc/us/index.html'
Results: 1
  1 (number): 0

io.popen: 	/usr/bin/stat -f '%A' 'doc/us/license.html'

os.execute: 	chmod '644' '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/doc/us/license.html'
Results: 1
  1 (number): 0

io.popen: 	/usr/bin/stat -f '%A' 'doc/us/luacrypto-128.png'

os.execute: 	chmod '644' '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/doc/us/luacrypto-128.png'
Results: 1
  1 (number): 0

io.popen: 	/usr/bin/stat -f '%A' 'doc/us/manual.html'

os.execute: 	chmod '644' '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/doc/us/manual.html'
Results: 1
  1 (number): 0

io.popen: 	/usr/bin/stat -f '%A' '/private/tmp/luarocks_luacrypto-0.3.2-1-3409/luacrypto-0.3.2-1.rockspec'

os.execute: 	chmod '644' '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/luacrypto-0.3.2-1.rockspec'
Results: 1
  1 (number): 0

io.popen: 	openssl md5 '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/doc/Makefile.am'

io.popen: 	openssl md5 '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/doc/Makefile.in'

io.popen: 	openssl md5 '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/doc/us/examples.html'

io.popen: 	openssl md5 '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/doc/us/index.html'

io.popen: 	openssl md5 '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/doc/us/license.html'

io.popen: 	openssl md5 '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/doc/us/luacrypto-128.png'

io.popen: 	openssl md5 '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/doc/us/manual.html'

io.popen: 	openssl md5 '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/lib/crypto.so'

io.popen: 	openssl md5 '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/luacrypto-0.3.2-1.rockspec'

io.popen: 	/usr/bin/stat -f '%A' '/usr/local/lib/luarocks/rocks/luacrypto/0.3.2-1/lib/crypto.so'

os.execute: 	chmod '755' '/usr/local/lib/lua/5.1/crypto.so'
Results: 1
  1 (number): 0
Updating manifest for /usr/local/lib/luarocks/rocks
luacrypto 0.3.2-1 is now built and installed in /usr/local (license: MIT)

**Comment by b-rajesh** [comment]
and then ran > brew reinstall kong > got same error
*******************************************
≥ brew reinstall kong                                                                                                                                                                                 16:09
==> Reinstalling mashape/kong/kong
==> Cloning https://github.com/Mashape/kong.git
Updating /Users/rajeshbavanantham/Library/Caches/Homebrew/kong--git
==> Checking out tag 0.8.3
==> make install
Last 15 lines from /Users/rajeshbavanantham/Library/Logs/Homebrew/kong/01.make:
lbase64 ~> 20120820-1
stringy ~> 0.4-1
mediator_lua ~> 1.1.2-0
lua-resty-iputils ~> 0.2.0-1
luasocket ~> 2.0.2-6
lua_uuid ~> 0.2.0-2


Error: Failed installing dependency: https://luarocks.org/luasec-0.5-2.src.rock - Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/local/include
  No file openssl/ssl.h in /usr/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local
Using https://luarocks.org/luasec-0.5-2.src.rock... switching to 'build' mode
make: *** [install] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/mashape/homebrew-kong/issues

These open issues may also help:
Kong 0.8.2 is not starting in OSX https://github.com/Mashape/homebrew-kong/issues/29

**Comment by syhily** [comment]
I thought it's a common issue for mac users.
```bash
# clean
brew remove kong
luarocks purge --tree /usr/local
brew link openssl --force

# source install
luarocks install luacrypto OPENSSL_DIR=/usr/local/opt/openssl
luarocks install luasec OPENSSL_DIR=/usr/local/opt/openssl
git clone https://github.com/Mashape/kong.git
cd kong
luarocks make kong-0.8.3-0.rockspec --verbose OPENSSL_DIR=/usr/local/opt/openssl
```

**Comment by syhily** [comment]
[kong-0.8.3-0.src.rock.zip](https://github.com/Mashape/homebrew-kong/files/297041/kong-0.8.3-0.src.rock.zip)
Or you can try using this prepacked rock.

**Comment by b-rajesh** [comment]
Thank you mate, 

this worked
# clean
brew remove kong
luarocks purge --tree /usr/local
brew link openssl --force

# source install
luarocks install luacrypto OPENSSL_DIR=/usr/local/opt/openssl
luarocks install luasec OPENSSL_DIR=/usr/local/opt/openssl
git clone https://github.com/Mashape/kong.git
cd kong
luarocks make kong-0.8.3-0.rockspec --verbose OPENSSL_DIR=/usr/local/opt/openssl
