### ISSUE TITLE
kong 0.9.0 not starting in mac

### ISSUE THREAD

**Issue by b-rajesh** [Mashape/homebrew-kong#32]
i installed kong 0.9.0 in mac and failed to start. help pls 

**************

/usr/local/share/lua/5.1/kong/cmd/start.lua:15: connection refused
stack traceback:
       	[C]: in function 'assert'
       	/usr/local/share/lua/5.1/kong/cmd/start.lua:15: in function 'cmd_exec'
       	/usr/local/share/lua/5.1/kong/cmd/init.lua:81: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:81>
       	[C]: in function 'xpcall'
       	/usr/local/share/lua/5.1/kong/cmd/init.lua:81: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:42>
       	/usr/local/bin/kong:11: in function 'file_gen'
       	init_worker_by_lua:38: in function <init_worker_by_lua:36>
       	[C]: in function 'pcall'
       	init_worker_by_lua:45: in function <init_worker_by_lua:43>

**Comment by thibaultcha** [comment]
Hey - sorry for the delay.

This appears to be an error in your connection to Postgres (the new default database for Kong). Ensure your Postgres server is running and accepting connections via TCP from your Kong node. 

Let me know if you still have issue, I'm closing this for now.

**Comment by b-rajesh** [comment]
I am getting different error after upgrading kong in mac to 0.9.1

/usr/local/bin/kong:7: module 'cassandra.socket' not found:
	no field package.preload['cassandra.socket']
	no file '/usr/local/Cellar/ngx_openresty/1.9.15.1/lualib/cassandra/socket.lua'
	no file '/usr/local/Cellar/ngx_openresty/1.9.15.1/lualib/cassandra/socket/init.lua'
	no file './cassandra/socket.lua'
	no file '/usr/local/Cellar/luajit/2.1_1/share/luajit-2.1.0-beta2/cassandra/socket.lua'
	no file '/usr/local/share/lua/5.1/cassandra/socket.lua'
	no file '/usr/local/share/lua/5.1/cassandra/socket/init.lua'
	no file '/usr/local/Cellar/luajit/2.1_1/share/lua/5.1/cassandra/socket.lua'
	no file '/usr/local/Cellar/luajit/2.1_1/share/lua/5.1/cassandra/socket/init.lua'
	no file '/usr/local/Cellar/ngx_openresty/1.9.15.1/lualib/cassandra/socket.so'
	no file './cassandra/socket.so'
	no file '/usr/local/lib/lua/5.1/cassandra/socket.so'
	no file '/usr/local/Cellar/luajit/2.1_1/lib/lua/5.1/cassandra/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/Cellar/ngx_openresty/1.9.15.1/lualib/cassandra.so'
	no file './cassandra.so'
	no file '/usr/local/lib/lua/5.1/cassandra.so'
	no file '/usr/local/Cellar/luajit/2.1_1/lib/lua/5.1/cassandra.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
