### ISSUE TITLE
Failed on building mashape/kong/serf

### ISSUE THREAD

**Issue by simonkuang** [Mashape/homebrew-kong#37]
There is the log named `01.make`.

    2016-10-02 00:18:04 +0800    

    make
    bin    

    find . -type f -name '.DS_Store' -delete
    go get github.com/mitchellh/gox
    go generate ./...
    go get -v -d -t ./...
    ==> Getting dependencies...
    ==> Removing old directory...
    ==> Building...
    Number of parallel builds: 3    

    -->    darwin/amd64: github.com/hashicorp/serf    

    1 errors occurred:
    --> darwin/amd64 error: exit status 2
    Stderr: # github.com/hashicorp/serf
    /usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64/link: -X flag requires argument of the form importpath.name=value    

    make: *** [bin] Error 1    

    HOMEBREW_VERSION: 1.0.5-49-gcc59e62
    ORIGIN: https://github.com/Homebrew/brew.git
    HEAD: cc59e624b05dbe227387c2f359deef6bfade3eb2
    Last commit: 2 hours ago
    Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
    Core tap HEAD: 97b6f9bdde21f1c51021ff2c2643be78d70a1e51
    Core tap last commit: 2 hours ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_REPOSITORY: /usr/local/Homebrew
    HOMEBREW_CELLAR: /usr/local/Cellar
    HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
    CPU: quad-core 64-bit ivybridge
    Homebrew Ruby: 2.0.0-p648
    GCC-4.2: build 0
    Clang: 8.0 build 800
    Git: 2.10.0 => /usr/local/opt/git/bin/git
    Perl: /usr/bin/perl
    Python: /usr/bin/python
    Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
    Java: 1.8.0_92, 1.8.0_60
    macOS: 10.12-x86_64
    Xcode: 8.0
    CLT: N/A
    X11: 2.7.8 => /opt/X11    

    HOMEBREW_CC: clang
    HOMEBREW_CXX: clang++
    SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
    MAKEFLAGS: -j4
    CMAKE_PREFIX_PATH: /usr/local
    CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/apache2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
    CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
    CMAKE_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks
    MACOSX_DEPLOYMENT_TARGET: 10.12
    PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
    HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
    ACLOCAL_PATH: /usr/local/share/aclocal
    PATH: /private/tmp/serf-20161002-8444-8jxkqw/gopath/bin:/usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/go/bin:/usr/local/opt/git/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by thibaultcha** [comment]
Kong 0.9.3 supports Serf 0.8 which should compile on OS X 10.12
