### ISSUE TITLE
kong 0.9.3 is not starting in mac

### ISSUE THREAD

**Issue by b-rajesh** [Mashape/homebrew-kong#38]
I have raised this issue with earlier version however it was closed without resolving the problem
When I attempt to start kong I am getting the following error

/usr/local/bin/kong:7: module 'cassandra.socket' not found:
    no field package.preload['cassandra.socket']
    no file '/usr/local/Cellar/ngx_openresty/1.11.2.1/site/lualib/cassandra/socket.lua'
    no file '/usr/local/Cellar/ngx_openresty/1.11.2.1/site/lualib/cassandra/socket/init.lua'
    no file '/usr/local/Cellar/ngx_openresty/1.11.2.1/lualib/cassandra/socket.lua'
    no file '/usr/local/Cellar/ngx_openresty/1.11.2.1/lualib/cassandra/socket/init.lua'
    no file './cassandra/socket.lua'
    no file '/usr/local/Cellar/luajit/2.1_1/share/luajit-2.1.0-beta2/cassandra/socket.lua'
    no file '/usr/local/share/lua/5.1/cassandra/socket.lua'
    no file '/usr/local/share/lua/5.1/cassandra/socket/init.lua'
    no file '/usr/local/Cellar/luajit/2.1_1/share/lua/5.1/cassandra/socket.lua'
    no file '/usr/local/Cellar/luajit/2.1_1/share/lua/5.1/cassandra/socket/init.lua'
    no file '/usr/local/Cellar/ngx_openresty/1.11.2.1/site/lualib/cassandra/socket.so'
    no file '/usr/local/Cellar/ngx_openresty/1.11.2.1/lualib/cassandra/socket.so'
    no file './cassandra/socket.so'
    no file '/usr/local/lib/lua/5.1/cassandra/socket.so'
    no file '/usr/local/Cellar/luajit/2.1_1/lib/lua/5.1/cassandra/socket.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
    no file '/usr/local/Cellar/ngx_openresty/1.11.2.1/site/lualib/cassandra.so'
    no file '/usr/local/Cellar/ngx_openresty/1.11.2.1/lualib/cassandra.so'
    no file './cassandra.so'
    no file '/usr/local/lib/lua/5.1/cassandra.so'
    no file '/usr/local/Cellar/luajit/2.1_1/lib/lua/5.1/cassandra.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'

---

mashape/kong/kong: stable 0.9.3, HEAD
Open-source Microservice and API Gateway
https://getkong.org
Conflicts with: cassandra
/usr/local/Cellar/kong/0.9.3 (6 files, 81.5K) *
  Built from source on 2016-10-29 at 21:26:01
From: https://github.com/mashape/homebrew-kong/blob/master/Formula/kong.rb
==> Dependencies
Required: openssl ✔, dnsmasq ✔, serf ✔, mashape/kong/luarocks ✔, mashape/kong/ngx_openresty ✔
==> Requirements
Build: git ✔

**Comment by thibaultcha** [comment]
Your issue (#32) was not closed without resolving the problem, but was about another problem you encountered and to which I gave you the solution. You then posted a new comment to it after it was closed instead of opening a new, separate issue, which is why you never got an answer (it simply got lost in the swarm of other opened issues).

Any logs from the install command in Homebrew? 

Would you provide the output of those commands:
```
# need 'tree'
$ tree /usr/local/share/lua/5.1/cassandra
```
and:
```
$ luarocks list
```

You can try this to fix your installation afterwards:
```
$ luarocks purge --tree=/usr/local
$ luarocks install kong 0.9.3
```

**Comment by b-rajesh** [comment]
Its my bad then to update the closed ticket. thank you for your swift response. I am wondering why it is still attempting cassandra when postgres is default database ? Please find the output as you requested.

**$  tree /usr/local/share/lua/5.1/cassandra**
/usr/local/share/lua/5.1/cassandra [error opening dir]

0 directories, 0 files

**$ luarocks list**

Installed rocks:
----------------

ansicolors
   1.0.2-3 (installed) - /usr/local/lib/luarocks/rocks

date
   2.1.2-1 (installed) - /usr/local/lib/luarocks/rocks

etlua
   1.3.0-1 (installed) - /usr/local/lib/luarocks/rocks

kong
   0.9.3-0 (installed) - /usr/local/lib/luarocks/rocks

lapis
   1.5.1-1 (installed) - /usr/local/lib/luarocks/rocks

loadkit
   1.1.0-1 (installed) - /usr/local/lib/luarocks/rocks

lpeg
   1.0.0-1 (installed) - /usr/local/lib/luarocks/rocks

lua-cassandra
   0.5.3-0 (installed) - /usr/local/lib/luarocks/rocks

lua-cjson
   2.1.0-1 (installed) - /usr/local/lib/luarocks/rocks

lua-resty-http
   0.08-0 (installed) - /usr/local/lib/luarocks/rocks

lua-resty-iputils
   0.2.1-1 (installed) - /usr/local/lib/luarocks/rocks

lua-resty-jit-uuid
   0.0.5-1 (installed) - /usr/local/lib/luarocks/rocks
   0.0.4-1 (installed) - /usr/local/lib/luarocks/rocks

lua_pack
   1.0.4-0 (installed) - /usr/local/lib/luarocks/rocks

lua_system_constants
   0.1.1-0 (installed) - /usr/local/lib/luarocks/rocks

luacrypto
   0.3.2-2 (installed) - /usr/local/lib/luarocks/rocks

luafilesystem
   1.6.3-2 (installed) - /usr/local/lib/luarocks/rocks

lualogging
   1.3.0-1 (installed) - /usr/local/lib/luarocks/rocks

luasec
   0.6-1 (installed) - /usr/local/lib/luarocks/rocks

luasocket
   3.0rc1-2 (installed) - /usr/local/lib/luarocks/rocks
   2.0.2-6 (installed) - /usr/local/lib/luarocks/rocks

luasyslog
   1.0.0-2 (installed) - /usr/local/lib/luarocks/rocks

luatz
   0.3-1 (installed) - /usr/local/lib/luarocks/rocks

mediator_lua
   1.1.2-0 (installed) - /usr/local/lib/luarocks/rocks

mimetypes
   1.0.0-1 (installed) - /usr/local/lib/luarocks/rocks

multipart
   0.3-2 (installed) - /usr/local/lib/luarocks/rocks

penlight
   1.3.2-2 (installed) - /usr/local/lib/luarocks/rocks

pgmoon
   1.6.0-1 (installed) - /usr/local/lib/luarocks/rocks

pgmoon-mashape
   2.0.0-1 (installed) - /usr/local/lib/luarocks/rocks
   1.7.0-1 (installed) - /usr/local/lib/luarocks/rocks

stringy
   0.4-1 (installed) - /usr/local/lib/luarocks/rocks

version
   0.2-1 (installed) - /usr/local/lib/luarocks/rocks

**Comment by b-rajesh** [comment]
When i try install luarocks I am getting the following

**$ luarocks install kong 0.9.3**
Installing https://luarocks.org/kong-0.9.3-0.rockspec
Missing dependencies for kong 0.9.3-0:
   luasec == 0.6 (not installed)
   luasocket == 2.0.2 (not installed)
   penlight == 1.3.2 (not installed)
   mediator_lua == 1.1.2 (not installed)
   lua-resty-http == 0.08 (not installed)
   lua-resty-jit-uuid == 0.0.5 (not installed)
   multipart == 0.4 (not installed)
   version == 0.2 (not installed)
   lapis == 1.5.1 (not installed)
   lua-cassandra == 0.5.4 (not installed)
   pgmoon-mashape == 2.0.0 (not installed)
   luatz == 0.3 (not installed)
   lua_system_constants == 0.1.1 (not installed)
   lua-resty-iputils == 0.2.1 (not installed)
   luacrypto == 0.3.2 (not installed)
   luasyslog == 1.0.0 (not installed)
   lua_pack == 1.0.4 (not installed)

kong 0.9.3-0 depends on luasec == 0.6 (not installed)
Installing https://luarocks.org/luasec-0.6-1.rockspec

Error: Failed installing dependency: https://luarocks.org/luasec-0.6-1.rockspec - Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/local/include
  No file openssl/ssl.h in /usr/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local

**Comment by thibaultcha** [comment]
Please follow the instructions given by luarocks and run the install command by specifying the correct `OPENSSL_DIR` as instructed.
