### ISSUE TITLE
Warning: Calling fails_with :llvm is deprecated!

### ISSUE THREAD

**Issue by Lao-liu** [Mashape/homebrew-kong#46]
Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/mashape/homebrew-kong/Formula/luarocks.rb:9:in `<class:Luarocks>'
Please report this to the mashape/kong tap!

**Comment by arcesino** [comment]
What was the resolution of this issue? I'm still experiencing the same warning

**Comment by thibaultcha** [comment]
I just pushed d26bf4aa175cdf6b2e3242e6e7ea5aac34b6f9d0 which removes the call to `fails_with` and thus this warning.
