### ISSUE TITLE
SHA256 mismatch when trying to install kong

### ISSUE THREAD

**Issue by shashank-jabong** [Mashape/homebrew-kong#8]
I was trying to install kong with cassandra but it is failing after cassandra is installed and kong is downloaded:

*XXX-MacBook-Pro:~ xxx$ brew install kong
==> Installing kong from mashape/homebrew-kong
==> Downloading https://github.com/Mashape/kong/archive/0.4.2.tar.gz
==> Downloading from https://codeload.github.com/Mashape/kong/tar.gz/0.4.2
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 838d7672275e23a1bebd763890bd840277657c18a9ddf9ad1ac75a49bf56c4b2
Actual: 9d7a1503e75ed7ffce702ca797d18b30783a62aa01884ec3f7f45873cad67fb8
Archive: /Library/Caches/Homebrew/kong-0.4.2.tar.gz
To retry an incomplete download, remove the file above.*

I have retried removing this tar file and re installing but still the same result. Can you check if your config and tar file's checksum is same on these mirrors?

**Comment by thibaultCha** [comment]
Indeed, that happened because of a rewrite of the Kong git repo. Thanks.
